### ISSUE TITLE
星级/保底/去重复算法设计思路

### ISSUE THREAD

**Issue by Regionnor** [cyanial/genshin-impact-picker#10]
这个抽卡点名器如何设置4星或5星呢 我这边体验到全是3星的
我希望能星星等级可以自己去调整

**Comment by cyanial** [comment]
代码中存在一些原来作者写的抽卡算法(用来模拟原神的抽卡), 但是这个算法不太适用于点名。

## 我设计了一种新的思路，同时解决一以下问题：

1. 抽到重复的人
2. 只有三星
3. 保底机制

## 描述一下我的设计思路：

(如果有人愿意可以实现, 修改 /src/helper/gocha/member.js相关文件)

1. 导入名单; 获得一个 `string list`, 使用者保证输入名单无重复。
2. 实现 `GenerateDrawPool()` 生成卡池;
3. 卡池内每个学生存一次, 随机选择一个人为5星, 随机几个人4星 (这里可以自定义).
4. 对卡池做 `RandomShuffle`(洗牌算法)
5. 抽卡的时候直接拿最后一个元素, 如果`n`抽就拿n个.
6. 抽到5星重新生成卡池.

## Misc.

同时可以做一个卡池的主页图片， 显示此次为5星的人物信息

**Comment by EvenWen1215** [comment]
现在有解决方案吗

**Comment by luyanci** [comment]
> 现在有解决方案吗

同问

**Comment by bxcZSZA** [comment]
除了会编辑代码文件以外其他都不懂，有大佬给一个具体怎么做的方案嘛
