### ISSUE TITLE
关于打包exe的问题

### ISSUE THREAD

**Issue by ulinxuanyu** [cyanial/genshin-impact-picker#11]
一枚小白。因为校园电脑系统为win7，且不能升级系统，所以想把electron降版本到21.4.4，按照README的步骤操作下来最后出错，是在electron-static目录下执行npm run build前把package.json里的版本号给换掉吗

**Comment by cyanial** [comment]
1. 清空 `node_modules`
2. 修改依赖的版本号
3. 修改 `npm run build` 命令 `electron-packager` 用到的 版本号

不建议，之前试过，应该要改代码，electron 好像新版本旧版本不兼容

**Comment by POTATORC** [comment]
> 1. 清空`node_modules`
> 2. 修改依赖的版本号
> 3. 修改  命令  用到的 版本号`npm run build``electron-packager`
> 
> 不建议，之前试过，应该要改代码，electron 好像新版本旧版本不兼容

![image](https://github.com/cyanial/genshin-impact-picker/assets/137894175/10e493fa-ed4f-4ccf-8eee-e6cf4f273745)
大佬可以帮我看看怎么回事吗

**Comment by luyanci** [comment]
> > 1. 清空`node_modules`
> > 2. 修改依赖的版本号
> > 3. 修改  命令  用到的 版本号`npm run build``electron-packager`
> > 
> > 不建议，之前试过，应该要改代码，electron 好像新版本旧版本不兼容
> 
> ![image](https://github.com/cyanial/genshin-impact-picker/assets/137894175/10e493fa-ed4f-4ccf-8eee-e6cf4f273745)
> 大佬可以帮我看看怎么回事吗

稍微看了一下 electron在**国内网络下**是会出现这种情况的

**Comment by luyanci** [comment]
可以直接fork这个仓库尝试修改`app.yml`和`electron-static/package.json`利用**github action**尝试构建exe程序

**Comment by luyanci** [comment]
> > 1. 清空`node_modules`
> > 2. 修改依赖的版本号
> > 3. 修改  命令  用到的 版本号`npm run build``electron-packager`
> > 
> > 不建议，之前试过，应该要改代码，electron 好像新版本旧版本不兼容
> 
> ![image](https://github.com/cyanial/genshin-impact-picker/assets/137894175/10e493fa-ed4f-4ccf-8eee-e6cf4f273745)
> 大佬可以帮我看看怎么回事吗

看#6
