### ISSUE TITLE
在electron-static中执行npm install

### ISSUE THREAD

**Issue by POTATORC** [cyanial/genshin-impact-picker#15]
![image](https://github.com/cyanial/genshin-impact-picker/assets/137894175/e52a5993-a53a-42f2-ac72-129bbb91f4d2)
打包exe的时候报错
有时候一个小白搞这个真的很无助，npm install怎么搞都报错，也看不懂这些错误，大佬们的文章也看不懂，救命

**Comment by luyanci** [comment]
你参考一下这篇[文章](https://www.bilibili.com/read/mobile?id=4789160)

**Comment by POTATORC** [comment]
> 你参考一下这篇[文章](https://www.bilibili.com/read/mobile?id=4789160)
谢谢大佬，但……
![image](https://github.com/cyanial/genshin-impact-picker/assets/137894175/09585b6e-ea40-452d-a9cf-ee43f5621a7d)

**Comment by POTATORC** [comment]
> 你参考一下这篇[文章](https://www.bilibili.com/read/mobile?id=4789160)

成功了！！！！！！！！！！谢大佬！！！！！！！！！！！！！！
