### ISSUE TITLE
抽人名单需要导入

### ISSUE THREAD

**Issue by bxcZSZA** [cyanial/genshin-impact-picker#16]
能否实现这样一个功能：将名单txt拖入到指定文件夹，再打开程序就不要再导入名单，池子里会直接有名单。
我觉得应该是可以实现的，但我是代码小白除了会编辑代码文件以外其他都不懂，求助一下有没有大佬能给个具体方案的。

**Comment by cyanial** [comment]
修改 electron 中的 express代码，相当于给后端加一个 fetch data 的api
