### ISSUE TITLE
下一步更新计划

### ISSUE THREAD

**Issue by cyanial** [cyanial/genshin-impact-picker#23]
# 1. 修复全屏/无法退出问题

> Q: 为什么程序现在不好关闭？
A: 我的 electron 里面包了一个 express, 这个express 用来托管网页 build 出来的 static 文件.  electron 打开后是去访问这个 express. (端口号是随机可用). 由于ui上的操作都是对网页而言的，所以没加关闭的功能。

修改思路：

1. express 写两个 api 一个用来关闭，另外一个用来切换fullscreen, electron 和 express 代码都在 `main.js` 里，应该比较好改。

2. 网页端可用把主页上右上角的按钮写成调用 express 关闭的api, 左上角问号旁边有个fullscreen的按钮可用做切换fullscreen.

## Misc.

这个思路应该可以做很多保存，读取相关的功能，比如导入照片等等。。。

# 2. 星级/保底/去重复

代码中存在一些原来作者写的抽卡算法(用来模拟原神的抽卡), 但是这个算法不太适用于点名。

## 我设计了一种新的思路，同时解决以下问题：

1. 抽到重复的人
2. 只有三星
3. 保底机制

## 描述一下我的设计思路：

(如果有人愿意可以实现, 修改 /src/helper/gocha/member.js相关文件)

1. 导入名单; 获得一个 `string list`, 使用者保证输入名单无重复。
2. 实现 `GenerateDrawPool()` 生成卡池;
3. 卡池内每个学生存一次, 随机选择一个人为5星, 随机几个人4星 (这里可以自定义).
4. 对卡池做 `RandomShuffle`(洗牌算法)
5. 抽卡的时候直接拿最后一个元素, 如果`n`抽就拿n个.
6. 抽到5星重新生成卡池.

## Misc.

同时可以做一个卡池的主页图片， 显示此次为5星的人物信息

**Comment by xianyubb** [comment]
就是提个建议，那个上传名单能不能改成永久上传，每次打开都要上传一次

**Comment by cyanial** [comment]
> 就是提个建议，那个上传名单能不能改成永久上传，每次打开都要上传一次

目前应该是可以缓存的，程序中通过 local storage 进行了存储。

**Comment by cyanial** [comment]
> 导入名单; 获得一个 string list, 使用者保证输入名单无重复。 实现 GenerateDrawPool() 生成卡池; 卡池内每个学生存一次, 随机选择一个人为5星, 随机几个人4星 (这里可以自定义). 对卡池做 RandomShuffle(洗牌算法) 抽卡的时候直接拿最后一个元素, 如果n抽就拿n个. 抽到5星重新生成卡池.
> 
> 太优秀了！！！但是这个要如何实现呢

https://unitychina.coding.net/public/uos/FuncStatelessDemo/git/files

工作中写过一个demo, 和这个类似，具体代码在`utils` 和 `actions` 中。

**Comment by Vinsonkang** [comment]
非常感谢，我学习一下




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cyanial/genshin-impact-picker"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月12日(星期二) 下午5:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cyanial/genshin-impact-picker] 下一步更新计划 (Issue #23)





  
导入名单; 获得一个 string list, 使用者保证输入名单无重复。 实现 GenerateDrawPool() 生成卡池; 卡池内每个学生存一次, 随机选择一个人为5星, 随机几个人4星 (这里可以自定义). 对卡池做 RandomShuffle(洗牌算法) 抽卡的时候直接拿最后一个元素, 如果n抽就拿n个. 抽到5星重新生成卡池.
 
太优秀了！！！但是这个要如何实现呢
  
https://unitychina.coding.net/public/uos/FuncStatelessDemo/git/files
 
工作中写过一个demo, 和这个类似，具体代码在utils 和 actions 中。

**Comment by Vinsonkang** [comment]
大佬，在我们学校的希沃白板上使用，系统是win7好像不能使用，会弹出报错，换了几个白板好像也不行，自己的win10电脑是可以的

错误信息：无法定位程序输入点 DiscardVirtualMemory于动态链接库KERNEL32.dll上

**Comment by cyanial** [comment]
> 大佬，在我们学校的希沃白板上使用，系统是win7好像不能使用，会弹出报错，换了几个白板好像也不行，自己的win10电脑是可以的
> 
> 错误信息：无法定位程序输入点 DiscardVirtualMemory于动态链接库KERNEL32.dll上

这个错误的原因是 `electron` 打包的可执行文件不兼容 `win7。

### 可能的解决方案：
- 本地起 server(可以参考代码里的 `express` )； 浏览器打开；
- 用 `tauri` 打包工具试试？

**Comment by ShawnNotFound** [comment]
这个算法如何保证10抽保底紫色，90抽保底金色？

**Comment by cyanial** [comment]
> 这个算法如何保证10抽保底紫色，90抽保底金色？

生成的卡池中放一个 金色物品，指定数量的紫色物品； 卡池一共90个物品，这样90抽保底金色；

10抽紫色的话，连抽10次，如果中间没有紫色就随机剔除一个元素去卡池了找一个紫色的物品。

**Comment by Maizi-G** [comment]
目前更新星级设定之后出现了星级与抽奖动画不绑定的情况，如果有大佬可以尝试吧动画和星级绑定

**Comment by luyanci** [comment]
目前软件全屏和退出问题已经在#17中修复完毕，其他的话目前除星数以外等待后续有人pr...

**Comment by luyanci** [comment]
话说回来，要不要先给仓库发个release？ :thinking_face:

**Comment by Maizi-G** [comment]
之前想过发，奈何没仓库权限

**Comment by Maizi-G** [comment]
星级绑定的更新有没有人测试过，貌似还没人打包

**Comment by luyanci** [comment]
> 之前想过发，奈何没仓库权限

+1好吧 action的release.yml还是在处于长期吃灰

**Comment by luyanci** [comment]
> 星级绑定的更新有没有人测试过，貌似还没人打包

https://github.com/cyanial/genshin-impact-picker/actions/runs/8323395373

🤔

**Comment by Maizi-G** [comment]
貌似那个公共站点只能选择放国外的站点，你敢放国内站不是被打就是被刷量，cf减速器竟然成了最佳选择（）

**Comment by Maizi-G** [comment]
希望能有大佬写个可以直接把名单直接上传到服务器目录的功能，学校电脑很多都有冰点还原，重启一次就得重新拷名单上传，一次性上传到服务器算是一劳永逸

**Comment by luyanci** [comment]
> 貌似那个公共站点只能选择放国外的站点，你敢放国内站不是被打就是被刷量，cf减速器竟然成了最佳选择（）
> 

我等周末放下我Netlify的链接(bushi

**Comment by Maizi-G** [comment]
> > 貌似那个公共站点只能选择放国外的站点，你敢放国内站不是被打就是被刷量，cf减速器竟然成了最佳选择（）
> 
> 我之前交的在线demo是挂在国外的，后续我可能挂一个到自己国内的服务器上试试水

不建议，我扔了个国外公开站，用的cf先运营个半年看看，国内站自用就行了，而且备案网站放这个公开可能会有合规问题

**Comment by luyanci** [comment]
> 希望能有大佬写个可以直接把名单直接上传到服务器目录的功能，学校电脑很多都有冰点还原，重启一次就得重新拷名单上传，一次性上传到服务器算是一劳永逸

感觉上有点难做…

**Comment by Maizi-G** [comment]
#16 这里面大佬提到过，但是没学过这个不会搞

**Comment by luyanci** [comment]
> #16 这里面大佬提到过，但是没学过这个不会搞

当时只有electron的打包，现在有Tauri还得额外适配

**Comment by ShawnNotFound** [comment]
> 希望能有大佬写个可以直接把名单直接上传到服务器目录的功能，学校电脑很多都有冰点还原，重启一次就得重新拷名单上传，一次性上传到服务器算是一劳永逸

其实可以直接把名单作为src的一部分，在index使用loadmembers把文件路径下面的名单加载进去，之前试过但是结果不是很理想，过段时间回家有了电脑再好好改一改试试，最近都是用手机调的代码

**Comment by Maizi-G** [comment]
让我多改改readme.md完善一下使用方法

**Comment by luyanci** [comment]
> 让我多改改readme.md完善一下使用方法

记得补一个从action下载app的提示

**Comment by Maizi-G** [comment]
我感觉如果我们多发发视频宣传这个源码这个仓库的star能破千

**Comment by ShawnNotFound** [comment]
> 让我多改改readme.md完善一下使用方法

其实我感觉这个适合出docs，这个项目有点过于依赖合作开发，然后代码构造的其实有点乱，如果有精力应该弄一些二次开发的指引，这样能吸引更多新来的开发者去改代码

**Comment by Maizi-G** [comment]
docs主要还是对开发者比较重要，但是用户一般只会去看readme现阶段貌似贡献者一共就7个人，我改了一下你们看看还有没有要加的内容
#44

**Comment by ShawnNotFound** [comment]
> 我感觉如果我们多发发视频宣传这个源码这个仓库的star能破千

我的想法是有机会弄一个访问快而且稳定的网站，这样能让更多人对这个项目有快捷的体验，才好进行下一步宣传。毕竟几百兆的安装包对于不太了解或者仅仅是想试一试的人来说不太友好，可能会把一些想用的人直接劝退了

**Comment by Maizi-G** [comment]
你要考虑成本问题，国内服务器成本可不低，其次国内服务器防御基本上都是一碰就死，还有这个源码就是基于大量动画素材，大小缩减太难，docker部署已经就是自动下载了，如果这样都懒得部署，那就别用了

**Comment by Maizi-G** [comment]
明天抽时间把镜像更新了，高中牲真的是太难了😥

**Comment by luyanci** [comment]
docker对普通用户还是有点复杂了吧…

**Comment by Maizi-G** [comment]
也不算多复杂吧，宝塔能自动装docker，命令自述里面也给了，跑一下加个反代的事，都接触服务器了，docker算是个最基本的工具吧，更别说像1panel这种基于docker运行的了

**Comment by ShawnNotFound** [comment]
> 你要考虑成本问题，国内服务器成本可不低，其次国内服务器防御基本上都是一碰就死，还有这个源码就是基于大量动画素材，大小缩减太难，docker部署已经就是自动下载了，如果这样都懒得部署，那就别用了

我手头有一个阿里云的，等到时候测一下够不够用，这种国内的就是宣传用，毕竟体验的人肯定不想每次打开都要加载好久，拉来用户，有了流量之后就会有更多的人来贡献和修改

**Comment by Maizi-G** [comment]
孩子高二了，平时连电脑都碰不上估计和你们对接不了，我看我找时间写个使用文档，开发文档部分你们完整读完代码的来写，我国内搞个文档站还是可以的，等我周六写吧，写好叫你们

**Comment by ShawnNotFound** [comment]
> 孩子高二了，平时连电脑都碰不上估计和你们对接不了，我看我找时间写个使用文档，开发文档部分你们完整读完代码的来写，我国内搞个文档站还是可以的，等我周六写吧，写好叫你们

好，周末我可以试一下能不能在国内配体验站，如果可以到时候我会发，要是有人有做视频之类的能力可以发视频然后挂国内链接和github仓库，给体验的人留个好印象
后续我再试一下预设名单文档的功能

**Comment by Maizi-G** [comment]
问题来了，搞在国内容易被盒啊。。。香港凑合一下吧

**Comment by Maizi-G** [comment]
或者我用aws东京，这玩意测速比国内服务器还快就离谱

**Comment by Maizi-G** [comment]
> > 孩子高二了，平时连电脑都碰不上估计和你们对接不了，我看我找时间写个使用文档，开发文档部分你们完整读完代码的来写，我国内搞个文档站还是可以的，等我周六写吧，写好叫你们
> 
> 好，周末我可以试一下能不能在国内配体验站，如果可以到时候我会发，要是有人有做视频之类的能力可以发视频然后挂国内链接和github仓库，给体验的人留个好印象 后续我再试一下预设名单文档的功能

我们周六的时候整个group交流一下？我觉得你可以整个首页，里面加上demo和git的跳转按钮，Github网址链接太长了

**Comment by ShawnNotFound** [comment]
> 问题来了，搞在国内容易被盒啊。。。香港凑合一下吧

没这么恶劣吧，我自己的一些站反正一年多了还没挂。
试试水，出了问题直接换源，到时候就能及时止损

**Comment by Maizi-G** [comment]
> > 问题来了，搞在国内容易被盒啊。。。香港凑合一下吧
> 
> 没这么恶劣吧，我自己的一些站反正一年多了还没挂。 试试水，出了问题直接换源，到时候就能及时止损

有幸被d过

**Comment by Maizi-G** [comment]
被d是小事，被c的话如果挂cdn会直接破产的（）

**Comment by ShawnNotFound** [comment]
> 被d是小事，被c的话如果挂cdn会直接破产的（）

周末试试，但愿没逝（

**Comment by Maizi-G** [comment]
gitbook好用还是docsify好用，好久没用过markdown了，语法都忘了

**Comment by Maizi-G** [comment]
不知道大佬能不能稍稍开放储存库权限

**Comment by luyanci** [comment]
> 不知道大佬能不能稍稍开放储存库权限

下放权限给几个较活跃的贡献者吧…

**Comment by cyanial** [comment]
> > 不知道大佬能不能稍稍开放储存库权限
> 
> 下放权限给几个较活跃的贡献者吧…

之前就想给了；因为修手机导致2FA验证过不了，一直拖到现在

**Comment by ShawnNotFound** [comment]
> > > 不知道大佬能不能稍稍开放储存库权限
> > 
> > 下放权限给几个较活跃的贡献者吧…
> 
> 之前就想给了；因为修手机导致2FA验证过不了，一直拖到现在

要不要考虑单开一个文档写更新计划，然后做完及时tick，这个版面的内容有点过时了

**Comment by cyanial** [comment]
> > > > 不知道大佬能不能稍稍开放储存库权限
> > > 
> > > 
> > > 下放权限给几个较活跃的贡献者吧…
> > 
> > 
> > 之前就想给了；因为修手机导致2FA验证过不了，一直拖到现在
> 
> 要不要考虑单开一个文档写更新计划，然后做完及时tick，这个版面的内容有点过时了

这个只是我当时的想法；有人更新的话 开个 Progressing 比较好; 

| 工作太忙了，做了初版后，就没时间维护了 😢

**Comment by luyanci** [comment]
给action放下权限吧，ci不能自动release…

**Comment by cyanial** [comment]
> 给action放下权限吧，ci不能自动把文件发到release…

done

**Comment by ShawnNotFound** [comment]
> > > > > 不知道大佬能不能稍稍开放储存库权限
> > > > 
> > > > 
> > > > 下放权限给几个较活跃的贡献者吧…
> > > 
> > > 
> > > 之前就想给了；因为修手机导致2FA验证过不了，一直拖到现在
> > 
> > 要不要考虑单开一个文档写更新计划，然后做完及时tick，这个版面的内容有点过时了
> 
> 这个只是我当时的想法；有人更新的话 开个 Progressing 比较好; 
> 
> | 工作太忙了，做了初版后，就没时间维护了 😢 

这么看我们三个高中牲时间还是相对充裕了，但是其实也有好多有思路想做的还没实现，只是初步改了一些bug

**Comment by cyanial** [comment]
调查一下， 你们对vue吗，有点像重构成 vue 的；而且原项目包含了很多用不到的内容，重构的同时精简一下代码

**Comment by ShawnNotFound** [comment]
> 调查一下， 你们对vue熟悉吗，有点想重构成 vue 的；而且原项目包含了很多用不到的内容，重构的同时精简一下代码

用过，但算不上熟悉
其实我在担心几个活跃contributer基本都是学生，时间不会很多，重构可能会有点困难

**Comment by cyanial** [comment]
> > 调查一下， 你们对vue熟悉吗，有点想重构成 vue 的；而且原项目包含了很多用不到的内容，重构的同时精简一下代码
> 
> 用过，但算不上熟悉 其实我在担心几个活跃contributor基本都是学生，时间不会很多，重构可能会有点困难

重构当然是我自己来写；应该可以做到并行，我自己单独弄个分支，不影响到目前项目，差不多后可以根据情况替换main

**Comment by cyanial** [comment]
当然只是随口说的，只是想看看如果重构成 vue； 大家能不能接受

**Comment by ShawnNotFound** [comment]
> 当然只是随口说的，只是想看看如果重构成 vue； 大家能不能接受

我应该没太大问题，一些基础的东西应该都能改改写写的

**Comment by ShawnNotFound** [comment]
感觉这个确实挺适合重构的，毕竟原作者的项目移植过来有好多没用的代码，感觉有点乱😅

**Comment by luyanci** [comment]
目前我先发个临时能用的release，防止有人找到后不知道怎么搞😢

**Comment by Maizi-G** [comment]
总得先试试才知道行不行不是吗

**Comment by Maizi-G** [comment]
我先吧文档仓库创建好，然后写完了以后在部署到国内写完之前先用gitbook的免费展示凑合一下

**Comment by Maizi-G** [comment]
我这边已经准备好文档的服务器了，但是需要一个备案域名，谁能解析一个过来

**Comment by Maizi-G** [comment]
文档用户部分写完了，还差开发部分，有没有佬来指点一下[doc](https://github.com/Maizi-G/genshin-impact-picker-doc)

**Comment by ShawnNotFound** [comment]
> 我这边已经准备好文档的服务器了，但是需要一个备案域名，谁能解析一个过来

给一下信息，我能解析过去

**Comment by Maizi-G** [comment]
你先给一下你的邮箱和准备解析的域名，我准备挂个cdn信息邮箱发你

**Comment by ShawnNotFound** [comment]
> 你先给一下你的邮箱和准备解析的域名，我准备挂个cdn信息邮箱发你

ssj13363381203@163.com
准备解析到
docs.picker.shawn404.top
如果有什么其他建议也可以换

**Comment by Maizi-G** [comment]
我这边是建议你吧哪个公开站域名换成demo-picker。。。。这个域名然后把picker-。。。。这个域名做为一个主页用

**Comment by ShawnNotFound** [comment]
> 我这边是建议你吧哪个公开站域名换成demo-picker。。。。这个域名然后把picker-。。。。这个域名做为一个主页用

OK，我去做修改，那就用picker.shawn404.top当docs域名

**Comment by Maizi-G** [comment]
不不不，我意思是，picker是一个主页，可以跳转到doc和demo

**Comment by ShawnNotFound** [comment]
> 不不不，我意思是，picker是一个主页，可以跳转到doc和demo

docs首页直接放一个所有人的demo的链接可以吗？

**Comment by Maizi-G** [comment]
你也可以

**Comment by Maizi-G** [comment]
那也可以

**Comment by Maizi-G** [comment]
加公开站页面了

**Comment by Maizi-G** [comment]
@ShawnNotFound edgeonereclaim主机记录
reclaim-kwgqtzhe5xzkc3j75v43nkgd60oo0g16记录值解析一下这个TXT记录，我加到cdn里面

**Comment by ShawnNotFound** [comment]
> @ShawnNotFound edgeonereclaim主机记录
> reclaim-kwgqtzhe5xzkc3j75v43nkgd60oo0g16记录值解析一下这个TXT记录，我加到cdn里面

done，看一下行不行
![Screenshot_20240322_124620_com.alibaba.aliyun.png](https://github.com/cyanial/genshin-impact-picker/assets/97796289/6cfead8a-6558-4f25-a6bf-1989201fae68)

**Comment by Maizi-G** [comment]
发你记录值了邮箱

**Comment by Maizi-G** [comment]
我要碎了，gitbook装不上

**Comment by Maizi-G** [comment]
救救我，卡死在install这一步，

**Comment by luyanci** [comment]
？

**Comment by Maizi-G** [comment]
@ShawnNotFound 看一下邮箱得改一下记录

**Comment by Maizi-G** [comment]
> 话说重构进度怎么样了啊…🤔

别急，重构是个大工程需要时间

**Comment by Maizi-G** [comment]
@cyanial 大佬考不考虑建个群，一直Github评论感觉好阴间

**Comment by luyanci** [comment]
> @cyanial 大佬考不考虑建个群，一直Github评论感觉好阴间

赞成

**Comment by cyanial** [comment]
![WechatIMG2](https://github.com/cyanial/genshin-impact-picker/assets/28806469/0b9ce985-3476-426e-a22d-604c2a4e935e)

**Comment by vipnetant** [comment]
希望解决的问题：
1、抽到重复的人
2、可以设置多个奖项，比如说特等奖、一等奖、二等奖……
3、每个奖项设置数量（现在可以改10抽为其他数量）

**Comment by Maizi-G** [comment]
> 希望解决的问题： 1、抽到重复的人 2、可以设置多个奖项，比如说特等奖、一等奖、二等奖…… 3、每个奖项设置数量（现在可以改10抽为其他数量）

这些问题解决方法很难实现，目前可以自定义星级，但是设置奖项这些需要修改动画的显示逻辑，添加新的配置项，新的素材，这些修改是有违这个点名器初衷的，这个点名器本身只是一种丰富课堂的方式，如果要抽奖你大可以找一些别的抽奖项目

**Comment by luyanci** [comment]
要不要把这个issue重新开一下吧🤔

**Comment by Maizi-G** [comment]
我觉得可以

**Comment by luyanci** [comment]
done
