### ISSUE TITLE
TypeError: redirects[builder.config.kit.trailingSlash] is not iterable

### ISSUE THREAD

**Issue by kerna60** [cyanial/genshin-impact-picker#4]
我是直接使用`npm run build`命令来生成exe文件，
卡在```
> Using @sveltejs/adapter-vercel
error during build:
TypeError: redirects[builder.config.kit.trailingSlash] is not iterable
```
这一步，小白确实不清楚应该怎么办，使用的是win11在cmd管理员环境下运行的
所有步骤在这个txt文件内

**Comment by kerna60** [comment]
[Clip_20240107_202941.txt](https://github.com/cyanial/genshin-impact-picker/files/13853503/Clip_20240107_202941.txt)

**Comment by cyanial** [comment]
我也有点问题，我升级了node 版本现在也编不出来了。

**Comment by cyanial** [comment]
看样子是软件版本的问题，你可以去git clone https://github.com/Mantan21/Genshin-Impact-Wish-Simulator 这个项目，试一下可以build不
