### ISSUE TITLE
制作用户使用文档以及开发文档

### ISSUE THREAD

**Issue by Maizi-G** [cyanial/genshin-impact-picker#47]
预计本周周末完成用户文档，开发者文档需要大家一起努力

**Comment by Maizi-G** [comment]
https://github.com/Maizi-G/genshin-impact-picker-doc/
要一起编写回复一下

**Comment by luyanci** [comment]
> https://github.com/Maizi-G/genshin-impact-picker-doc/
> 要一起编写回复一下

1

**Comment by Maizi-G** [comment]
docs.mznet.pro
