### ISSUE TITLE
在点名界面（芙宁娜）点击设置卡死

### ISSUE THREAD

**Issue by QAQ2333333** [cyanial/genshin-impact-picker#55]
在点名界面（芙宁娜）点击设置卡死，不能进行任何操作，只能退出重新进入不知道是为什么

**Comment by luyanci** [comment]
@cyanial

**Comment by luyanci** [comment]
> 在点名界面（芙宁娜）点击设置卡死，不能进行任何操作，只能退出重新进入不知道是为什么

因为点名卡池的设置根本没有做🤔
