### ISSUE TITLE
如何更改卡池展示图片？

### ISSUE THREAD

**Issue by windyslime** [cyanial/genshin-impact-picker#56]
如题 想把卡池那张图片更换成我们自定义的图片应该改哪个文件？

**Comment by luyanci** [comment]
#23

**Comment by luyanci** [comment]
>> 希望解决的问题： 1、抽到重复的人 2、可以设置多个奖项，比如说特等奖、一等奖、二等奖…… 3、每个奖项设置数量（现在可以改10抽为其他数量）

> 这些问题解决方法很难实现，目前可以自定义星级，但是设置奖项这些需要修改动画的显示逻辑，添加新的配置项，新的素材，这些修改是有违这个点名器初衷的，这个点名器本身只是一种丰富课堂的方式，如果要抽奖你大可以找一些别的抽奖项目

**Comment by Maizi-G** [comment]
如为最新版本修改网站目录下的/internal/immutable/assets/chanson-of-many-waters-1-812cf393.webp文件即可
