### ISSUE TITLE
建议添加自动更新代码工作流

### ISSUE THREAD

**Issue by ZSOF-Rui** [cyanial/genshin-impact-picker#57]
建议启用在Workflows中启用Upstream Sync以实现下游代码自动更新

**Comment by ZSOF-Rui** [comment]
不知道这个可行性如何😂
https://github.com/aormsby/Fork-Sync-With-Upstream-action

**Comment by luyanci** [comment]
> 不知道这个可行性如何😂
> https://github.com/aormsby/Fork-Sync-With-Upstream-action
> 

大概看了一下，似乎不可行
- 这个action功能只是检测，并不能做到更新
- 被检测分支的提交要像[这样子](https://github.com/luyanci/genshin-impact-picker-fork/tree/dev)，才可以正确检测到是否有更新

**Comment by Maizi-G** [comment]
@luyanci 我有个想法，在workflow里加入自动生成并推送docker镜像，docker提供了在镜像更新时自动更新镜像的服务

**Comment by Maizi-G** [comment]
也就是Watchtower，如果觉得这个可行qq上滴滴我，我发给你我dockerhub的秘钥

**Comment by luyanci** [comment]
> @luyanci 我有个想法，在workflow里加入自动生成并推送docker镜像，docker提供了在镜像更新时自动更新镜像的服务

这个我本来就有打算，奈何不会玩docker…

**Comment by Maizi-G** [comment]
手动更新docker镜像太草了
奈何我不会写workflow.....

**Comment by luyanci** [comment]
> 也就是Watchtower，如果觉得这个可行qq上滴滴我，我发给你我dockerhub的秘钥
> 

dockerhub秘钥暂时先不用，workflow要用的话得让@cyanial 加到仓库设置里

**Comment by Maizi-G** [comment]
#59 等大佬加入秘钥什么的就行了，此外请使用文档里的dockercomposer部署方式来实现自动更新
