### ISSUE TITLE
星级抽风

### ISSUE THREAD

**Issue by arkting** [cyanial/genshin-impact-picker#58]
3星冒金光，5星是蓝的，有时候十连紫色又全是蓝的。
但是另几个卡池是正常的，只有自定义名单的卡池抽风

**Comment by luyanci** [comment]
#40 的改动没有生效吗？

**Comment by Maizi-G** [comment]
您确定您使用的是最新版本吗，能不能把你上传的名单展示一下 @arkting

**Comment by arkting** [comment]
> 您确定您使用的是最新版本吗，能不能把你上传的名单展示一下 @arkting

5 A
B

抽卡动画大概率A是蓝色的，未标注的B是金色的

**Comment by arkting** [comment]
> #40 的改动没有生效吗？ (请详细说明一下**使用方式** )

用的是dm.mznet.pro，名单：
5 A
B

A的动画是蓝色的，B未标注反而是金色的

**Comment by luyanci** [comment]
> > #40 的改动没有生效吗？ (请详细说明一下**使用方式** )
> 
> 用的是dm.mznet.pro，名单：
> 5 A
> B
> 
> A的动画是蓝色的，B未标注反而是金色的

@Maizi-G 这个你解释一下了

**Comment by Maizi-G** [comment]
稍等
我试试复现

**Comment by cyanial** [comment]
我最一开始的版本动画的光是随机的，和抽到的卡的级别没有关系。后面他们应该修改过

**Comment by Maizi-G** [comment]
出现这个情况因为dm.mznet.pro这个网站没有同步动画与星级绑定的更新，刚刚我已经进行这个这个更新，如果还出现以上情况，请重新开启这个issue

**Comment by Maizi-G** [comment]
推荐还是使用自己搭建的站点或者使用构建好的应用程序，公共站点可能会疏于管理可以去看文档
[文档](https://docs.mznet.pro)

**Comment by arkting** [comment]
> 出现这个情况因为dm.mznet.pro这个网站没有同步动画与星级绑定的更新，刚刚我已经进行这个这个更新，如果还出现以上情况，请重新开启这个issue

更新放到晚上吧😵刚刚我们班上用着用着就403了

**Comment by luyanci** [comment]
> > 出现这个情况因为dm.mznet.pro这个网站没有同步动画与星级绑定的更新，刚刚我已经进行这个这个更新，如果还出现以上情况，请重新开启这个issue
> 
> 更新放到晚上吧😵刚刚我们班上用着用着就403了

哈哈哈，下次尽量使用本地方案，不然遇到这种事情很尴尬的

**Comment by Maizi-G** [comment]
> > 出现这个情况因为dm.mznet.pro这个网站没有同步动画与星级绑定的更新，刚刚我已经进行这个这个更新，如果还出现以上情况，请重新开启这个issue
> 
> 更新放到晚上吧😵刚刚我们班上用着用着就403了

刚刚换了一台服务器
（）
