### ISSUE TITLE
关于README补充的建议

### ISSUE THREAD

**Issue by jiangyin14** [cyanial/genshin-impact-picker#6]
新手，没明白这种有vite成分的非纯js项目应该如何正确编译运行（？）
使用最新版WebStorm+node.js v18打开项目文件夹，npm run build会直接失败，疑似没有编制相关的索引（？），如果可以的话，希望开发者能简述一下编译的流程，这样二次开发会更顺手一些，谢谢(🙏ˊᗜˋ*)

**Comment by cyanial** [comment]
两个项目。一个是svelte的前端项目，这个build失败的话，建议看看 svelte-kit 的文档，或者更新一下版本。这个npm run dev 就能预览，npm run build 构建出静态文件。

electron相关的是把静态文件打包成 .exe 如果只要二次开发，应该可以不用管，直接用上面的调试就可以了。

**Comment by jiangyin14** [comment]
> 两个项目。一个是svelte的前端项目，这个build失败的话，建议看看 svelte-kit 的文档，或者更新一下版本。这个npm run dev 就能预览，npm run build 构建出静态文件。
> 
> 
> 
> electron相关的是把静态文件打包成 .exe 如果只要二次开发，应该可以不用管，直接用上面的调试就可以了。

请问执行所需的工作目录应该是哪里？

**Comment by cyanial** [comment]
```bash
$ cd Genshin-Impact-Wish-Simulator
$ npm install
$ npm run dev 
$ npm run build
```

**Comment by jiangyin14** [comment]
> ```bash
> 
> $ cd Genshin-Impact-Wish-Simulator
> 
> $ npm install
> 
> $ npm run dev 
> 
> $ npm run build
> 
> ```

关于在npm i指令安装依赖的时候，sharp下载libvips时所出现的证书问题应该如何解决？

![image](https://github.com/cyanial/genshin-impact-picker/assets/106649516/b8fbd650-d26b-44df-a823-f9589bab66bb)
完整错误log见Pastebin
https://pastebin.com/raw/HvmNTskR


使用Windows系统的云服务器也复现同样问题，参考了很多的StackOverflow，CSDN和Github issue，但是所有方法（cnpm，换源，挂梯子，提前下载本地文件做替换，设置不验证证书的环境变量和npm的config）全部没能奏效，比较苦恼。
您是否有解决类似问题的经验？

**Comment by cyanial** [comment]
好像比较少遇到下载的问题。

命令行开代理了吗：

`export https_proxy=http://127.0.0.1:7890 http_proxy=http://127.0.0.1:7890 all_proxy=socks5://127.0.0.1:7890`

**Comment by jiangyin14** [comment]
> 好像比较少遇到下载的问题。
> 
> 
> 
> 命令行开代理了吗：
> 
> 
> 
> `export https_proxy=http://127.0.0.1:7890 http_proxy=http://127.0.0.1:7890 all_proxy=socks5://127.0.0.1:7890` 
> 
> 
> 
> 

这个是Linux（shell）的命令吧，我是windows的话是不是用git bash这样也可以？

**Comment by cyanial** [comment]
windows:
`set HTTS_PROXY=http://127.0.0.1:7890 ...`

**Comment by jiangyin14** [comment]
> windows:
> 
> `set HTTS_PROXY=http://127.0.0.1:7890 ...`

打错字了（？），没效果哈

**Comment by cyanial** [comment]
你端口选你的代理的端口，改完后试试 curl google.com， 不是404 就是好了

**Comment by jiangyin14** [comment]
好的 我试试看

**Comment by jiangyin14** [comment]
您发的是CMD所使用的命令，确实是可以的。这里再补充一个PowerShell所使用的命令

’’’
$env:HTTP_PROXY="http://127.0.0.1:7890"; $env:HTTPS_PROXY="http://127.0.0.1:7890"
’’’

是Clash默认端口，根据个人设置可进行更改
