### ISSUE TITLE
Tauri构建反馈

### ISSUE THREAD

**Issue by luyanci** [cyanial/genshin-impact-picker#60]
在pr #34 中，给Win7及以上系统尝试做了兼容支持，需要看到本issue的各位反馈一下(特别需要**Win7用户**反馈，正常运行也说一下，麻烦了)

## 反馈格式(后面提bug的都需要参考这个)
```
操作系统：
使用方式：
(如果使用公共站点或者自行部署网站的，请贴上链接，并附上使用的浏览器)
描述：(这里就可以开始说明了)
```

> Tips:主要是这边暂时没有win7系统的设备可以测试…

**Comment by Maizi-G** [comment]
冷知识，我现在用的设备是win7

**Comment by Maizi-G** [comment]
冷知识，我现在用的设备是win7

**Comment by luyanci** [comment]
> 冷知识，我现在用的设备是win7

好家伙
