### ISSUE TITLE
[BUG]electron app 卡在connection

### ISSUE THREAD

**Issue by skyworldp** [cyanial/genshin-impact-picker#67]
### BUG描述(文字/截图/视频)

electron app 卡在connection

### 一些相关信息

win11 最新版electron

### 预期行为(文字/截图/视频)

进入抽卡页面

### 实际行为(文字/截图/视频)

卡在第一屏

**Comment by cyanial** [comment]
端口 9989 被占用了吗

**Comment by cyanial** [comment]
1. 端口占用
2. 清理缓存 （electron 菜单中的开发者模式 -> 应用 清理所有缓存)
