### ISSUE TITLE
修复全屏/无法退出问题的思路

### ISSUE THREAD

**Issue by luyanci** [cyanial/genshin-impact-picker#8]
- 1.应用程序无法关闭(没有关闭按钮/关闭按钮无效)
- 2.打开app时可能无法全屏/退出全屏

**Comment by cyanial** [comment]
Q: 为什么不好关闭？
A: 我的 electron 里面包了一个 express, 这个express 用来托管网页 build 出来的 static 文件.  electron 打开后是去访问这个 express. (端口号是随机可用). 由于ui上的操作都是对网页而言的，所以没加关闭的功能。

修改思路：

1. express 写两个 api 一个用来关闭，另外一个用来切换fullscreen, electron 和 express 代码都在 `main.js` 里，应该比较好改。

2. 网页端可用把主页上右上角的按钮写成调用 express 关闭的api, 左上角问号旁边有个fullscreen的按钮可用做切换fullscreen.

## Misc.

这个思路应该可以做很多保存，读取相关的功能，比如导入照片等等。。。

**Comment by luyanci** [comment]
还是谢谢大佬解释了，不过我对nodejs和vite只是了解怎么用，没有怎么深入了解。
不过我在`main.js`中把

```
win.setFullScreen(true);
```

改成了

```
 win.setFullScreen(false);
```

这样子应该可以暂时缓解上面这些bug(要关闭，就直接右键在任务栏的程序关闭就好了)

**Comment by bxcZSZA** [comment]
除了会编辑代码文件以外其他都不懂，有大佬能给一个具体怎么做才能让右上角按钮拥有实际关闭的效果嘛
